# name: Update Readme
# on:
#   schedule:
#     - cron: "0 0 * * *"
#   workflow_dispatch:

# jobs:
#   update-readme:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Update Readme with WakaTime Stats
#         uses: iehtian/waka-readme-stats@master
#         with:
#           WAKATIME_API_KEY: ${{ secrets.WAKAPI_API_KEY }}
#           GH_TOKEN: ${{ secrets.METRICS_TOKEN }}
#           WAKAPI_BASE_URL: "http://wakapi.陈莹.我爱你/api"
#           SHOW_LINES_OF_CODE: "True"
#           SHOW_PROFILE_VIEWS: "False"
#           SHOW_COMMIT: "True"
#           SHOW_DAYS_OF_WEEK: "True"
#           SHOW_LANGUAGE: "True"
#           SHOW_OS: "False"
#           SHOW_PROJECTS: "True"
#           SHOW_TIMEZONE: "False"
#           SHOW_EDITORS: "True"
#           SHOW_LANGUAGE_PER_REPO: "False"
#           SHOW_SHORT_INFO: "True"
#           SHOW_LOC_CHART: "True"
#           SHOW_UPDATED_DATE: "True"
#           SHOW_TOTAL_CODE_TIME: "True"
